In [4]:
import tensorflow as tf
import numpy as np

In [5]:
def MinMaxScaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

# Normalized inputs( min-max scale)

In [6]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

In [7]:
xy = MinMaxScaler(xy)
print(xy)

[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


In [8]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [9]:
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([4,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [10]:
hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [11]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [12]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  0.17511576 
Prediction:
 [[ 0.11531392]
 [ 0.82293236]
 [ 0.39561668]
 [-0.08727002]
 [ 0.15699193]
 [ 0.18355837]
 [-0.08958535]
 [ 0.16689974]]
1 Cost:  0.17510766 
Prediction:
 [[ 0.11533147]
 [ 0.8229475 ]
 [ 0.39562953]
 [-0.08725964]
 [ 0.15700412]
 [ 0.18357003]
 [-0.08957785]
 [ 0.16690648]]
2 Cost:  0.17509952 
Prediction:
 [[ 0.11534902]
 [ 0.82296264]
 [ 0.39564243]
 [-0.08724925]
 [ 0.1570163 ]
 [ 0.18358174]
 [-0.08957039]
 [ 0.16691318]]
3 Cost:  0.17509142 
Prediction:
 [[ 0.11536658]
 [ 0.8229777 ]
 [ 0.39565533]
 [-0.08723886]
 [ 0.1570285 ]
 [ 0.18359339]
 [-0.08956289]
 [ 0.16691989]]
4 Cost:  0.17508331 
Prediction:
 [[ 0.11538413]
 [ 0.8229928 ]
 [ 0.3956683 ]
 [-0.08722848]
 [ 0.15704069]
 [ 0.18360507]
 [-0.08955541]
 [ 0.1669266 ]]
5 Cost:  0.1750752 
Prediction:
 [[ 0.11540163]
 [ 0.82300794]
 [ 0.39568114]
 [-0.08721811]
 [ 0.15705287]
 [ 0.18361676]
 [-0.0895479 ]
 [ 0.16693333]]
6 Cost:  0.17506711 
Prediction:
 [[ 0.11541918]
 [ 0.8230232 ]
 [ 0.39

197 Cost:  0.17353186 
Prediction:
 [[ 0.11875141]
 [ 0.8258909 ]
 [ 0.3981441 ]
 [-0.08523358]
 [ 0.15937668]
 [ 0.18584618]
 [-0.08811632]
 [ 0.1682156 ]]
198 Cost:  0.17352387 
Prediction:
 [[ 0.11876878]
 [ 0.8259058 ]
 [ 0.3981569 ]
 [-0.08522332]
 [ 0.15938881]
 [ 0.1858578 ]
 [-0.0881089 ]
 [ 0.16822228]]
199 Cost:  0.17351589 
Prediction:
 [[ 0.11878622]
 [ 0.8259208 ]
 [ 0.3981696 ]
 [-0.08521301]
 [ 0.15940085]
 [ 0.1858693 ]
 [-0.08810145]
 [ 0.16822892]]
200 Cost:  0.1735079 
Prediction:
 [[ 0.11880359]
 [ 0.8259357 ]
 [ 0.39818242]
 [-0.08520266]
 [ 0.15941292]
 [ 0.18588093]
 [-0.08809403]
 [ 0.16823557]]
201 Cost:  0.17349991 
Prediction:
 [[ 0.11882102]
 [ 0.8259506 ]
 [ 0.39819524]
 [-0.08519238]
 [ 0.15942499]
 [ 0.18589249]
 [-0.08808661]
 [ 0.16824222]]
202 Cost:  0.17349193 
Prediction:
 [[ 0.1188384 ]
 [ 0.8259655 ]
 [ 0.39820793]
 [-0.08518207]
 [ 0.15943703]
 [ 0.18590403]
 [-0.08807914]
 [ 0.16824886]]
203 Cost:  0.17348395 
Prediction:
 [[ 0.11885577]
 [ 0.825

377 Cost:  0.17210376 
Prediction:
 [[ 0.1218732 ]
 [ 0.8285748 ]
 [ 0.40043768]
 [-0.08338511]
 [ 0.16154137]
 [ 0.18792269]
 [-0.08678353]
 [ 0.16940838]]
378 Cost:  0.17209591 
Prediction:
 [[ 0.12189049]
 [ 0.8285897 ]
 [ 0.40045026]
 [-0.08337487]
 [ 0.1615533 ]
 [ 0.18793413]
 [-0.08677614]
 [ 0.16941497]]
379 Cost:  0.172088 
Prediction:
 [[ 0.12190783]
 [ 0.8286046 ]
 [ 0.400463  ]
 [-0.08336464]
 [ 0.16156524]
 [ 0.18794563]
 [-0.08676879]
 [ 0.16942155]]
380 Cost:  0.17208013 
Prediction:
 [[ 0.12192512]
 [ 0.82861936]
 [ 0.40047565]
 [-0.08335443]
 [ 0.1615772 ]
 [ 0.18795708]
 [-0.08676142]
 [ 0.16942814]]
381 Cost:  0.17207223 
Prediction:
 [[ 0.1219424 ]
 [ 0.82863426]
 [ 0.4004884 ]
 [-0.08334419]
 [ 0.16158924]
 [ 0.18796867]
 [-0.08675405]
 [ 0.16943473]]
382 Cost:  0.17206436 
Prediction:
 [[ 0.12195969]
 [ 0.82864916]
 [ 0.4005011 ]
 [-0.08333395]
 [ 0.16160119]
 [ 0.18798009]
 [-0.08674669]
 [ 0.16944131]]
383 Cost:  0.1720565 
Prediction:
 [[ 0.12197697]
 [ 0.82866

526 Cost:  0.1709348 
Prediction:
 [[ 0.12444484]
 [ 0.830786  ]
 [ 0.40232646]
 [-0.08186357]
 [ 0.16332364]
 [ 0.18963248]
 [-0.08568713]
 [ 0.17038935]]
527 Cost:  0.17092702 
Prediction:
 [[ 0.12446201]
 [ 0.83080065]
 [ 0.40233907]
 [-0.0818534 ]
 [ 0.16333553]
 [ 0.18964383]
 [-0.0856798 ]
 [ 0.17039591]]
528 Cost:  0.17091924 
Prediction:
 [[ 0.12447912]
 [ 0.8308155 ]
 [ 0.40235168]
 [-0.08184324]
 [ 0.16334742]
 [ 0.1896553 ]
 [-0.08567248]
 [ 0.17040244]]
529 Cost:  0.17091146 
Prediction:
 [[ 0.12449628]
 [ 0.8308302 ]
 [ 0.40236422]
 [-0.08183308]
 [ 0.1633594 ]
 [ 0.18966666]
 [-0.08566515]
 [ 0.170409  ]]
530 Cost:  0.17090368 
Prediction:
 [[ 0.12451345]
 [ 0.830845  ]
 [ 0.4023769 ]
 [-0.08182295]
 [ 0.1633713 ]
 [ 0.18967813]
 [-0.08565784]
 [ 0.17041555]]
531 Cost:  0.1708959 
Prediction:
 [[ 0.12453061]
 [ 0.8308598 ]
 [ 0.4023895 ]
 [-0.08181278]
 [ 0.16338313]
 [ 0.18968949]
 [-0.0856505 ]
 [ 0.1704221 ]]
532 Cost:  0.17088813 
Prediction:
 [[ 0.12454778]
 [ 0.8308

687 Cost:  0.1696878 
Prediction:
 [[ 0.12720293]
 [ 0.83315897]
 [ 0.40435353]
 [-0.08023049]
 [ 0.16523632]
 [ 0.19146708]
 [-0.08450978]
 [ 0.17144343]]
688 Cost:  0.1696801 
Prediction:
 [[ 0.12721997]
 [ 0.8331735 ]
 [ 0.4043661 ]
 [-0.0802204 ]
 [ 0.16524819]
 [ 0.19147846]
 [-0.08450247]
 [ 0.17144996]]
689 Cost:  0.1696724 
Prediction:
 [[ 0.12723708]
 [ 0.8331883 ]
 [ 0.40437862]
 [-0.08021028]
 [ 0.16525999]
 [ 0.19148976]
 [-0.08449517]
 [ 0.17145649]]
690 Cost:  0.16966471 
Prediction:
 [[ 0.12725413]
 [ 0.83320296]
 [ 0.4043912 ]
 [-0.08020017]
 [ 0.16527182]
 [ 0.19150117]
 [-0.08448789]
 [ 0.17146301]]
691 Cost:  0.16965702 
Prediction:
 [[ 0.12727118]
 [ 0.8332176 ]
 [ 0.40440372]
 [-0.08019005]
 [ 0.16528368]
 [ 0.1915125 ]
 [-0.08448061]
 [ 0.17146954]]
692 Cost:  0.16964933 
Prediction:
 [[ 0.12728828]
 [ 0.8332323 ]
 [ 0.40441623]
 [-0.08017996]
 [ 0.16529551]
 [ 0.19152394]
 [-0.08447334]
 [ 0.17147607]]
693 Cost:  0.16964164 
Prediction:
 [[ 0.12730533]
 [ 0.83324

883 Cost:  0.16818842 
Prediction:
 [[ 0.13054329]
 [ 0.8360243 ]
 [ 0.40680322]
 [-0.07825473]
 [ 0.16754958]
 [ 0.19368586]
 [-0.08308695]
 [ 0.1727142 ]]
884 Cost:  0.16818082 
Prediction:
 [[ 0.13056031]
 [ 0.8360389 ]
 [ 0.4068157 ]
 [-0.07824466]
 [ 0.16756132]
 [ 0.19369715]
 [-0.0830797 ]
 [ 0.17272067]]
885 Cost:  0.16817322 
Prediction:
 [[ 0.13057733]
 [ 0.8360535 ]
 [ 0.40682814]
 [-0.0782346 ]
 [ 0.16757306]
 [ 0.19370848]
 [-0.08307245]
 [ 0.17272714]]
886 Cost:  0.1681656 
Prediction:
 [[ 0.13059434]
 [ 0.83606803]
 [ 0.40684062]
 [-0.07822454]
 [ 0.1675849 ]
 [ 0.19371974]
 [-0.08306521]
 [ 0.1727336 ]]
887 Cost:  0.16815796 
Prediction:
 [[ 0.13061142]
 [ 0.8360827 ]
 [ 0.4068531 ]
 [-0.07821445]
 [ 0.16759667]
 [ 0.1937311 ]
 [-0.08305797]
 [ 0.17274007]]
888 Cost:  0.16815037 
Prediction:
 [[ 0.13062844]
 [ 0.8360973 ]
 [ 0.4068656 ]
 [-0.07820439]
 [ 0.16760844]
 [ 0.1937424 ]
 [-0.08305073]
 [ 0.17274654]]
889 Cost:  0.16814278 
Prediction:
 [[ 0.13064542]
 [ 0.836

1083 Cost:  0.16668108 
Prediction:
 [[ 0.13392687]
 [ 0.83892477]
 [ 0.40928307]
 [-0.07625441]
 [ 0.16989145]
 [ 0.19593206]
 [-0.08164728]
 [ 0.17399922]]
1084 Cost:  0.1666736 
Prediction:
 [[ 0.13394374]
 [ 0.83893925]
 [ 0.40929538]
 [-0.07624446]
 [ 0.16990316]
 [ 0.1959432 ]
 [-0.08164011]
 [ 0.17400563]]
1085 Cost:  0.16666614 
Prediction:
 [[ 0.13396055]
 [ 0.8389536 ]
 [ 0.4093077 ]
 [-0.0762345 ]
 [ 0.16991475]
 [ 0.19595447]
 [-0.08163294]
 [ 0.174012  ]]
1086 Cost:  0.16665865 
Prediction:
 [[ 0.13397741]
 [ 0.83896816]
 [ 0.40932012]
 [-0.07622452]
 [ 0.16992652]
 [ 0.19596562]
 [-0.08162576]
 [ 0.17401841]]
1087 Cost:  0.16665117 
Prediction:
 [[ 0.13399428]
 [ 0.8389826 ]
 [ 0.40933242]
 [-0.07621455]
 [ 0.16993812]
 [ 0.19597682]
 [-0.08161861]
 [ 0.17402482]]
1088 Cost:  0.1666437 
Prediction:
 [[ 0.13401109]
 [ 0.83899695]
 [ 0.40934485]
 [-0.0762046 ]
 [ 0.16994983]
 [ 0.19598803]
 [-0.08161141]
 [ 0.17403123]]
1089 Cost:  0.16663623 
Prediction:
 [[ 0.13402796]
 [

1263 Cost:  0.16534337 
Prediction:
 [[ 0.1369504 ]
 [ 0.8415178 ]
 [ 0.41149968]
 [-0.07446668]
 [ 0.17198464]
 [ 0.1979397 ]
 [-0.08036041]
 [ 0.17514828]]
1264 Cost:  0.16533598 
Prediction:
 [[ 0.13696715]
 [ 0.8415322 ]
 [ 0.41151196]
 [-0.07445675]
 [ 0.1719963 ]
 [ 0.19795078]
 [-0.08035326]
 [ 0.17515466]]
1265 Cost:  0.16532859 
Prediction:
 [[ 0.1369839 ]
 [ 0.84154654]
 [ 0.4115243 ]
 [-0.07444684]
 [ 0.17200786]
 [ 0.19796193]
 [-0.08034614]
 [ 0.17516103]]
1266 Cost:  0.1653212 
Prediction:
 [[ 0.13700071]
 [ 0.8415609 ]
 [ 0.41153657]
 [-0.07443693]
 [ 0.17201948]
 [ 0.19797304]
 [-0.08033898]
 [ 0.17516741]]
1267 Cost:  0.16531381 
Prediction:
 [[ 0.13701746]
 [ 0.84157526]
 [ 0.41154885]
 [-0.07442702]
 [ 0.17203104]
 [ 0.19798416]
 [-0.08033186]
 [ 0.17517379]]
1268 Cost:  0.16530642 
Prediction:
 [[ 0.13703421]
 [ 0.8415896 ]
 [ 0.4115612 ]
 [-0.0744171 ]
 [ 0.1720427 ]
 [ 0.1979953 ]
 [-0.08032471]
 [ 0.17518017]]
1269 Cost:  0.16529901 
Prediction:
 [[ 0.13705096]
 

1424 Cost:  0.1641602 
Prediction:
 [[ 0.13964212]
 [ 0.8438261 ]
 [ 0.4134726 ]
 [-0.07287627]
 [ 0.17384744]
 [ 0.19972622]
 [-0.07921623]
 [ 0.17616963]]
1425 Cost:  0.1641529 
Prediction:
 [[ 0.13965878]
 [ 0.8438403 ]
 [ 0.41348475]
 [-0.07286642]
 [ 0.17385894]
 [ 0.19973725]
 [-0.07920918]
 [ 0.17617592]]
1426 Cost:  0.16414562 
Prediction:
 [[ 0.13967544]
 [ 0.8438546 ]
 [ 0.4134969 ]
 [-0.07285662]
 [ 0.17387044]
 [ 0.19974828]
 [-0.0792021 ]
 [ 0.17618221]]
1427 Cost:  0.16413832 
Prediction:
 [[ 0.1396921 ]
 [ 0.8438689 ]
 [ 0.41350913]
 [-0.07284679]
 [ 0.17388195]
 [ 0.1997593 ]
 [-0.07919505]
 [ 0.17618847]]
1428 Cost:  0.16413105 
Prediction:
 [[ 0.13970876]
 [ 0.8438831 ]
 [ 0.41352123]
 [-0.07283694]
 [ 0.17389345]
 [ 0.19977033]
 [-0.07918799]
 [ 0.17619476]]
1429 Cost:  0.16412373 
Prediction:
 [[ 0.13972542]
 [ 0.8438973 ]
 [ 0.4135334 ]
 [-0.07282713]
 [ 0.17390496]
 [ 0.19978142]
 [-0.07918096]
 [ 0.17620102]]
1430 Cost:  0.16411643 
Prediction:
 [[ 0.13974208]
 [

 [ 0.17716071]]
1583 Cost:  0.16300708 
Prediction:
 [[ 0.14228249]
 [ 0.846082  ]
 [ 0.4154029 ]
 [-0.07131705]
 [ 0.17567205]
 [ 0.20147586]
 [-0.07809564]
 [ 0.17716697]]
1584 Cost:  0.16299991 
Prediction:
 [[ 0.14229897]
 [ 0.84609616]
 [ 0.41541502]
 [-0.07130732]
 [ 0.17568344]
 [ 0.20148686]
 [-0.07808864]
 [ 0.17717323]]
1585 Cost:  0.16299269 
Prediction:
 [[ 0.1423155 ]
 [ 0.8461103 ]
 [ 0.4154271 ]
 [-0.07129754]
 [ 0.17569488]
 [ 0.20149776]
 [-0.07808161]
 [ 0.17717943]]
1586 Cost:  0.16298549 
Prediction:
 [[ 0.14233205]
 [ 0.8461243 ]
 [ 0.41543916]
 [-0.07128778]
 [ 0.1757063 ]
 [ 0.20150873]
 [-0.0780746 ]
 [ 0.17718568]]
1587 Cost:  0.16297829 
Prediction:
 [[ 0.14234859]
 [ 0.8461385 ]
 [ 0.4154513 ]
 [-0.07127801]
 [ 0.17571774]
 [ 0.20151967]
 [-0.07806757]
 [ 0.17719194]]
1588 Cost:  0.16297112 
Prediction:
 [[ 0.14236507]
 [ 0.84615266]
 [ 0.4154633 ]
 [-0.07126828]
 [ 0.17572913]
 [ 0.20153067]
 [-0.07806057]
 [ 0.1771982 ]]
1589 Cost:  0.16296393 
Prediction:


 [[ 0.14556539]
 [ 0.8488878 ]
 [ 0.41780353]
 [-0.06937854]
 [ 0.17794085]
 [ 0.20365152]
 [-0.07670251]
 [ 0.17840725]]
1783 Cost:  0.1615756 
Prediction:
 [[ 0.14558184]
 [ 0.8489018 ]
 [ 0.4178155 ]
 [-0.06936881]
 [ 0.1779522 ]
 [ 0.2036624 ]
 [-0.0766955 ]
 [ 0.17841348]]
1784 Cost:  0.16156846 
Prediction:
 [[ 0.14559835]
 [ 0.84891593]
 [ 0.4178276 ]
 [-0.06935909]
 [ 0.17796355]
 [ 0.2036733 ]
 [-0.07668853]
 [ 0.17841971]]
1785 Cost:  0.16156135 
Prediction:
 [[ 0.1456148 ]
 [ 0.84893006]
 [ 0.4178396 ]
 [-0.06934939]
 [ 0.17797494]
 [ 0.20368421]
 [-0.07668155]
 [ 0.17842591]]
1786 Cost:  0.16155423 
Prediction:
 [[ 0.14563125]
 [ 0.84894407]
 [ 0.41785157]
 [-0.06933966]
 [ 0.17798635]
 [ 0.20369515]
 [-0.07667455]
 [ 0.17843214]]
1787 Cost:  0.16154712 
Prediction:
 [[ 0.1456477 ]
 [ 0.8489581 ]
 [ 0.41786367]
 [-0.06932995]
 [ 0.17799771]
 [ 0.20370609]
 [-0.07666759]
 [ 0.17843837]]
1788 Cost:  0.16153999 
Prediction:
 [[ 0.14566422]
 [ 0.8489722 ]
 [ 0.41787577]
 [-0.06

 [ 0.1795834 ]]
1973 Cost:  0.16023296 
Prediction:
 [[ 0.1486994 ]
 [ 0.85156643]
 [ 0.42009464]
 [-0.06752938]
 [ 0.1801059 ]
 [ 0.20572773]
 [-0.07537426]
 [ 0.17958957]]
1974 Cost:  0.16022594 
Prediction:
 [[ 0.1487157 ]
 [ 0.85158026]
 [ 0.42010656]
 [-0.06751971]
 [ 0.18011716]
 [ 0.20573857]
 [-0.07536733]
 [ 0.17959571]]
1975 Cost:  0.16021897 
Prediction:
 [[ 0.148732  ]
 [ 0.8515943 ]
 [ 0.42011842]
 [-0.06751011]
 [ 0.18012846]
 [ 0.20574924]
 [-0.07536045]
 [ 0.17960188]]
1976 Cost:  0.16021198 
Prediction:
 [[ 0.14874831]
 [ 0.85160816]
 [ 0.42013034]
 [-0.0675005 ]
 [ 0.18013969]
 [ 0.20576015]
 [-0.07535353]
 [ 0.17960805]]
1977 Cost:  0.16020498 
Prediction:
 [[ 0.14876461]
 [ 0.8516221 ]
 [ 0.42014226]
 [-0.06749088]
 [ 0.18015096]
 [ 0.20577088]
 [-0.07534662]
 [ 0.17961419]]
1978 Cost:  0.16019797 
Prediction:
 [[ 0.14878091]
 [ 0.85163605]
 [ 0.42015412]
 [-0.06748123]
 [ 0.18016225]
 [ 0.20578173]
 [-0.0753397 ]
 [ 0.17962036]]
1979 Cost:  0.16019098 
Prediction:
