# 1차원 배열

In [21]:
import numpy as np
import matplotlib.pylab as plt

In [21]:
A = np.array([1,2,3,4])

In [22]:
print(A)

[1 2 3 4]


In [23]:
np.ndim(A)

1

In [24]:
A.shape

(4,)

In [33]:
A.shape[0]

4

# 2차원배열

In [34]:
B = np.array([[1,2],[3,4],[5,6]])

In [35]:
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [36]:
np.ndim(B)

2

In [37]:
B.shape

(3, 2)

In [38]:
B.shape[0]

3

In [39]:
B.shape[1]

2

# 행렬의 곱

In [40]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [41]:
A.shape

(2, 2)

In [42]:
B.shape

(2, 2)

In [43]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [44]:
A*B

array([[ 5, 12],
       [21, 32]])

In [46]:
C = np.array([[1,2,3],[4,5,6]])
D = np.array([[1,2],[3,4],[5,6]])

In [47]:
C.shape

(2, 3)

In [48]:
D.shape

(3, 2)

In [49]:
np.dot(C,D)

array([[22, 28],
       [49, 64]])

In [74]:
np.dot(C,A)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [51]:
np.dot(A,C)

array([[ 9, 12, 15],
       [19, 26, 33]])

# 신경망에서의 행렬 곱

In [53]:
X = np.array([1,2])
W = np.array([[1,3,5],[2,4,6]])

In [56]:
print(X)
print(W)

[1 2]
[[1 3 5]
 [2 4 6]]


In [59]:
Y = np.dot(X,W)
print(Y)

[ 5 11 17]


# 신호전달 0->1

In [67]:
X = np.array([1.0,0.5])
W1 = np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
B1 = np.array([0.1,0.2,0.3])

In [68]:
print(W1.shape)
print(X.shape)
print(B1.shape)

(2, 3)
(2,)
(3,)


In [81]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [82]:
A1 = np.dot(X,W1) + B1
Z1 = sigmoid(A1)

In [83]:
print(A1)
print(Z1)

[ 0.3  0.7  1.1]
[ 0.57444252  0.66818777  0.75026011]


# 신호전달 1->2

In [84]:
W2 = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
B2 = np.array([0.1,0.2])

In [85]:
print(Z1.shape)
print(W2.shape)
print(B2.shape)

(3,)
(3, 2)
(2,)


In [86]:
A2 = np.dot(Z1,W2)+B2
Z2 = sigmoid(A2)

# 신호전달 2->output

In [88]:
def identity_function(x):
    return x

In [89]:
W3 = np.array([[0.1,0.3],[0.2,0.4]])
B3 = np.array([0.1,0.2])

In [91]:
A3 = np.dot(Z2,W3)+B3
Y = identity_function(A3)

In [92]:
print(Y)

[ 0.57855079  0.66736228]


# 구현정리

In [93]:
def init_network():
    network = {}
    network['W1'] = np.array([[0.1,0.3,0.5],
                              [0.2,0.4,0.6]])
    network['B1'] = np.array([0.1,0.2,0.3])
    network['W2'] = np.array([[0.1,0.4],
                              [0.2,0.5],
                              [0.3,0.6]])
    network['B2'] = np.array([0.1,0.2])
    network['W3'] = np.array([[0.1,0.3],
                              [0.2,0.4]])
    network['B3'] = np.array([0.1,0.2])
    
    return network

In [96]:
def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    B1, B2, B3 = network['B1'], network['B2'], network['B3']
    
    a1 = np.dot(x, W1) + B1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + B2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + B3
    y = identity_function(a3)
    
    return y

In [97]:
network = init_network()
x = np.array([1.0,0.5])
y = forward(network,x)
print(y)

[ 0.31682708  0.69627909]


# softmax

In [23]:
a = np.array([0.3,2.9,4.0])
exp_a = np.exp(a)
print(exp_a)

[  1.34985881  18.17414537  54.59815003]


In [24]:
sum_exp_a = np.sum(exp_a)
print(sum_exp_a)

74.1221542102


In [25]:
y = exp_a / sum_exp_a
print(y)

[ 0.01821127  0.24519181  0.73659691]


In [26]:
def softmax_(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y

In [27]:
print(softmax_([0.3,2.9,4.0]))

[ 0.01821127  0.24519181  0.73659691]


# softmax without overflow

In [28]:
a = np.array([1010,1000,990])
np.exp(a) / np.sum(np.exp(a))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([ nan,  nan,  nan])

In [29]:
c = np.max(a)
a-c

array([  0, -10, -20])

In [30]:
np.exp(a-c) / np.sum(np.exp(a-c))

array([  9.99954600e-01,   4.53978686e-05,   2.06106005e-09])

In [31]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a-c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y

In [32]:
softmax([1010,1000,990])

array([  9.99954600e-01,   4.53978686e-05,   2.06106005e-09])

# feature of softmax

In [33]:
a = np.array([0.3,2.9,4.0])
y = softmax(a)
print(y)
print(np.sum(y))

[ 0.01821127  0.24519181  0.73659691]
1.0


# 손글씨 숫자인식_ MNIST 데이터셋

In [34]:
import sys, os
sys.path.append(os.pardir)
from dataset.mnist import load_mnist

In [35]:
(x_train, t_train),(x_test,t_test) = load_mnist(flatten=True, normalize=False)

In [36]:
print(x_train.shape)
print(t_train.shape)
print(x_test.shape)
print(t_test.shape)

(60000, 784)
(60000,)
(10000, 784)
(10000,)
