In [2]:
import sys, os
sys.path.append(os.pardir)
import numpy as np
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient

In [3]:
class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2,3)
        
    def predict(self,x):
        return np.dot(x, self.W)
    
    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)
        
        return loss

In [15]:
net = simpleNet()
print(net.W)

[[-1.27129518  0.29012917  0.89527694]
 [ 0.09309732  0.92536007  1.08602502]]


In [16]:
x = np.array([0.6,0.9])
p = net.predict(x)
print(p)

[-0.67898952  1.00690156  1.51458868]


In [17]:
np.argmax(p)

2

In [18]:
t = np.array([0,0,1])
net.loss(x,t)

0.53848131800564647

In [21]:
# def f(W):
#     return net.loss(x,t)
# 간단한 함수는 lambda 기법을 써도된다
f = lambda W: net.loss(x,t)

In [22]:
dW = numerical_gradient(f,net.W)
print(dW)

[[ 0.03905105  0.21076861 -0.24981966]
 [ 0.05857658  0.31615291 -0.37472949]]
