In [11]:
import tensorflow as tf

In [12]:
x_data = [[73.,80.,75.],[93.,88.,93.],[89.,91.,90.],[96.,98.,100.],[73.,66.,70.]]
y_data = [[152.],[185.],[180.],[196.],[142.]]

In [13]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [14]:
W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [15]:
hypothesis = tf.matmul(X, W) + b

In [16]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [17]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [18]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [19]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  73519.695 
Prediction:
 [[ -86.966095]
 [-105.91412 ]
 [-103.52667 ]
 [-114.22017 ]
 [ -79.89802 ]]
10 Cost:  2.5464232 
Prediction:
 [[152.88527]
 [182.3788 ]
 [180.52832]
 [195.1093 ]
 [139.99869]]
20 Cost:  1.8645239 
Prediction:
 [[153.60599]
 [183.25453]
 [181.38625]
 [196.04425]
 [140.66841]]
30 Cost:  1.8556898 
Prediction:
 [[153.60315]
 [183.2606 ]
 [181.3873 ]
 [196.0461 ]
 [140.6748 ]]
40 Cost:  1.8469391 
Prediction:
 [[153.59816]
 [183.264  ]
 [181.38574]
 [196.0451 ]
 [140.67917]]
50 Cost:  1.8382099 
Prediction:
 [[153.59317]
 [183.26743]
 [181.3842 ]
 [196.04411]
 [140.68353]]
60 Cost:  1.8295349 
Prediction:
 [[153.5882 ]
 [183.27081]
 [181.38264]
 [196.04312]
 [140.68788]]
70 Cost:  1.8209165 
Prediction:
 [[153.58322]
 [183.2742 ]
 [181.38113]
 [196.04214]
 [140.69221]]
80 Cost:  1.8123347 
Prediction:
 [[153.57828]
 [183.27757]
 [181.3796 ]
 [196.04117]
 [140.69655]]
90 Cost:  1.8038279 
Prediction:
 [[153.57336]
 [183.28094]
 [181.37808]
 [196.04019]
 [140

920 Cost:  1.2344792 
Prediction:
 [[153.20668]
 [183.53125]
 [181.26431]
 [195.96852]
 [141.0204 ]]
930 Cost:  1.2290685 
Prediction:
 [[153.20276]
 [183.53394]
 [181.26309]
 [195.96777]
 [141.02382]]
940 Cost:  1.2236745 
Prediction:
 [[153.19882]
 [183.5366 ]
 [181.26187]
 [195.96701]
 [141.02724]]
950 Cost:  1.2183154 
Prediction:
 [[153.1949 ]
 [183.53928]
 [181.26067]
 [195.96628]
 [141.03064]]
960 Cost:  1.2129629 
Prediction:
 [[153.191  ]
 [183.54195]
 [181.25943]
 [195.96552]
 [141.03404]]
970 Cost:  1.2076623 
Prediction:
 [[153.1871 ]
 [183.5446 ]
 [181.25822]
 [195.96475]
 [141.03743]]
980 Cost:  1.2023876 
Prediction:
 [[153.18321]
 [183.54726]
 [181.25702]
 [195.964  ]
 [141.04079]]
990 Cost:  1.1971371 
Prediction:
 [[153.17934]
 [183.5499 ]
 [181.25581]
 [195.96326]
 [141.04416]]
1000 Cost:  1.1919141 
Prediction:
 [[153.17546]
 [183.55254]
 [181.25462]
 [195.96252]
 [141.04752]]
1010 Cost:  1.1867105 
Prediction:
 [[153.1716 ]
 [183.55518]
 [181.25342]
 [195.96179]
 [

1730 Cost:  0.8774618 
Prediction:
 [[152.91933]
 [183.72722]
 [181.17494]
 [195.91405]
 [141.26904]]
1740 Cost:  0.8739642 
Prediction:
 [[152.91615]
 [183.72937]
 [181.17395]
 [195.91345]
 [141.27176]]
1750 Cost:  0.8704716 
Prediction:
 [[152.91298]
 [183.73152]
 [181.17296]
 [195.91286]
 [141.27449]]
1760 Cost:  0.86700547 
Prediction:
 [[152.90982]
 [183.73366]
 [181.17197]
 [195.91228]
 [141.2772 ]]
1770 Cost:  0.86355317 
Prediction:
 [[152.90668]
 [183.73582]
 [181.171  ]
 [195.9117 ]
 [141.27992]]
1780 Cost:  0.860109 
Prediction:
 [[152.90355]
 [183.73798]
 [181.17001]
 [195.91112]
 [141.28264]]
1790 Cost:  0.85669976 
Prediction:
 [[152.90042]
 [183.74011]
 [181.16905]
 [195.91055]
 [141.28534]]
1800 Cost:  0.8532931 
Prediction:
 [[152.89728]
 [183.74223]
 [181.16806]
 [195.90996]
 [141.28802]]
1810 Cost:  0.84991807 
Prediction:
 [[152.89417]
 [183.74435]
 [181.16708]
 [195.90936]
 [141.2907 ]]
1820 Cost:  0.8465716 
Prediction:
 [[152.89107]
 [183.74646]
 [181.16612]
 [19