In [1]:
import tensorflow as tf

In [2]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

In [3]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

In [4]:
w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [5]:
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [6]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [8]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [9]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [11]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  5.4703293 
Prediction:
 [147.62268 187.0867  179.2435  197.1588  143.38611]
10 Cost:  5.447689 
Prediction:
 [147.63077 187.08119 179.24605 197.16013 143.37933]
20 Cost:  5.425191 
Prediction:
 [147.63884 187.07573 179.2486  197.16145 143.37259]
30 Cost:  5.4027824 
Prediction:
 [147.64688 187.07025 179.25113 197.16275 143.36584]
40 Cost:  5.3804884 
Prediction:
 [147.65492 187.0648  179.25365 197.16405 143.35915]
50 Cost:  5.3583403 
Prediction:
 [147.66292 187.05937 179.25618 197.16534 143.35245]
60 Cost:  5.3362565 
Prediction:
 [147.67091 187.05394 179.2587  197.16663 143.34576]
70 Cost:  5.3143497 
Prediction:
 [147.67888 187.04854 179.26118 197.16792 143.33913]
80 Cost:  5.2925224 
Prediction:
 [147.68683 187.04314 179.26369 197.16922 143.33249]
90 Cost:  5.270832 
Prediction:
 [147.69475 187.03777 179.26619 197.1705  143.32587]
100 Cost:  5.2492213 
Prediction:
 [147.70265 187.03238 179.26866 197.17177 143.31926]
110 Cost:  5.227748 
Prediction:
 [147.71056 187.02705 17

960 Cost:  3.7601752 
Prediction:
 [148.31017 186.62042 179.46054 197.26611 142.8162 ]
970 Cost:  3.7464855 
Prediction:
 [148.31645 186.61613 179.46251 197.26703 142.81102]
980 Cost:  3.7329094 
Prediction:
 [148.32274 186.61192 179.46452 197.26799 142.8059 ]
990 Cost:  3.7193794 
Prediction:
 [148.32898 186.60767 179.46649 197.26889 142.80075]
1000 Cost:  3.7059014 
Prediction:
 [148.33524 186.60344 179.46849 197.26982 142.79564]
1010 Cost:  3.6925113 
Prediction:
 [148.34146 186.59923 179.47044 197.27072 142.79054]
1020 Cost:  3.6792202 
Prediction:
 [148.34766 186.59503 179.47241 197.27164 142.78546]
1030 Cost:  3.6659744 
Prediction:
 [148.35385 186.59085 179.4744  197.27255 142.7804 ]
1040 Cost:  3.6527848 
Prediction:
 [148.36002 186.58665 179.47633 197.27342 142.77533]
1050 Cost:  3.6396828 
Prediction:
 [148.36618 186.58249 179.4783  197.27435 142.7703 ]
1060 Cost:  3.6266499 
Prediction:
 [148.37231 186.57832 179.48024 197.27525 142.76526]
1070 Cost:  3.613659 
Prediction:
 [

1900 Cost:  2.7406037 
Prediction:
 [148.83507 186.26541 179.62749 197.3393  142.39049]
1910 Cost:  2.7321978 
Prediction:
 [148.83997 186.26205 179.62904 197.33992 142.38652]
1920 Cost:  2.723824 
Prediction:
 [148.84491 186.25877 179.63063 197.34059 142.38261]
1930 Cost:  2.7154944 
Prediction:
 [148.8498  186.25545 179.63219 197.3412  142.3787 ]
1940 Cost:  2.7071962 
Prediction:
 [148.85468 186.25214 179.63374 197.34181 142.37479]
1950 Cost:  2.6989722 
Prediction:
 [148.85954 186.24886 179.6353  197.34245 142.3709 ]
1960 Cost:  2.6907632 
Prediction:
 [148.86441 186.24557 179.63684 197.34308 142.367  ]
1970 Cost:  2.6826231 
Prediction:
 [148.86925 186.24231 179.6384  197.3437  142.36314]
1980 Cost:  2.67449 
Prediction:
 [148.8741  186.23906 179.63997 197.34433 142.35928]
1990 Cost:  2.6664186 
Prediction:
 [148.87892 186.23581 179.6415  197.34494 142.35545]
2000 Cost:  2.6583858 
Prediction:
 [148.88371 186.23254 179.64302 197.34554 142.3516 ]
